/* for wijmo controls
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.analytics.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.animation.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.annotation.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.finance.analytics.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.finance.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.hierarchical.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.chart.interaction.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.gauge.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.detail.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.filter.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.grouppanel.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.multirow.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.pdf.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.sheet.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.grid.xlsx.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.input.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.odata.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.olap.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.pdf.d.ts" />
/// <reference path="../node_modules/wijmo/controls/wijmo.xlsx.d.ts" />
*/